version: "3.8"
services:
  postgres:
    image: postgres
    container_name: supernotifier_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - ${PWD}/docker/postgres/data:/var/lib/postgresql/data
      - ${PWD}/docker/postgres/backups:/root/backups
    ports:
      - "5432:5432"
    networks:
      - supernotifier
  redis:
    image: redis:alpine
    container_name: supernotifier_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - ${PWD}/docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - supernotifier
networks:
  supernotifier:
    name: supernotifier
    driver: bridge