version: "3.8"
services:
  postgres:
    image: postgres
    container_name: supernotifier_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PWD}/docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - supernotifier
  redis:
    image: redis:alpine
    container_name: supernotifier_redis
    restart: always
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - ${PWD}/docker/redis:/data
    ports:
      - "6379:6379"
    networks:
      - supernotifier
networks:
  supernotifier:
    driver: bridge